version: '3'
services:
  database:
    image: mongo
    ports:
      - '27037:27017'
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
    volumes:
      - ./database:/data/db
  frontend:
    build: frontend
    environment:
      - REACT_APP_BACKEND_SERVER_URL=http://localhost:5000
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - ./frontend:/app
    depends_on:
      - backend
  backend:
    build: backend
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - DB_CONNECT=mongodb://database:27017/flashcardapp
    volumes:
      - /app/node_modules
      - ./backend:/app
    depends_on:
      database:
        condition: service_healthy
  open-api-doc:
    build: open-api-doc
    ports:
      - '4000:4000'
